import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Providers } from "./providers";
import { ClientLayout } from "./clientLayout";

export const metadata: Metadata = {
  title: "Neves Jr",
  description: "Generated by create next app",
};

export const monumentFontFamily = localFont({
  src: "../../public/fonts/MonumentExtended-Regular.otf",
  variable: "--font-monument",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={monumentFontFamily.variable}>
      <body>
        <Providers>
          <ClientLayout>{children}</ClientLayout>
        </Providers>
      </body>
    </html>
  );
}
